parse issue body

diff --git a/.github/workflows/issue.yml b/.github/workflows/issue.yml
--- a/.github/workflows/issue.yml
+++ b/.github/workflows/issue.yml
@@ -22,12 +22,18 @@ jobs:
       - name: install resumed and jsonresume-theme-even package
         run: npm install resumed jsonresume-theme-even
   
-      - name: Save Issue Body to File
+      - name: Extract and Parse JSON Issue Body
         run: |
-          ISSUE_BODY=$(echo "${{ github.event.issue.body }}" | sed 's/"/\\"/g')
+          ISSUE_BODY=${{ github.event.issue.body }}
+          echo "$ISSUE_BODY" > resume.json
 
-      - name: create a resume.json file with the body of the issue
-        run: echo "$ISSUE_BODY" > resume.json
+          # Validate JSON format
+          if jq empty resume.json 2>/dev/null; then
+            echo "Valid JSON detected. Parsing..."
+          else
+            echo "Error: Issue body is not valid JSON!" >&2
+            exit 1
+          fi
 
       - name: validate resume.json file
         run: npx resumed validate resume.json
